version: "2"
services:
  elasticsearch:
    image: elasticsearch:7.9.1
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  cortex:
    image: thehiveproject/cortex:3.1.0-1
    depends_on:
      - elasticsearch
    ports:
      - "0.0.0.0:9001:9001"
    volumes:
      - cortex-data:/app/data

  thehive:
    image: thehiveproject/thehive:3.5.0-1
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - "0.0.0.0:9000:9000"
    command: --cortex-port 9001
    volumes:
      - thehive-data:/app/data

volumes:
  elasticsearch-data:
  cortex-data:
  thehive-data:
