version: "3"
services:
  thehive:
    image: strangebee/thehive:5.2
    restart: unless-stopped
    depends_on:
      - cassandra
      - elasticsearch
      - minio
      - cortex
    mem_limit: 1500m
    ports:
      - "9000:9000"
    environment:
      - JVM_OPTS="-Xms1024M -Xmx1024M"
    command:
      - --secret
      - "mySecretForTheHive"
      - "--cql-hostnames"
      - "cassandra"
      - "--index-backend"
      - "elasticsearch"
      - "--es-hostnames"
      - "elasticsearch"
      #- "--s3-endpoint"
      #- "http://minio:9000"
      #- "--s3-access-key"
      #- "minioadmin"
      #- "--s3-secret-key"
      #- "minioadmin"
      #- "--s3-bucket"
      #- "thehive"
      #- "--s3-use-path-access-style"
      - "--cortex-hostnames"
      - "cortex"
      #- "--cortex-keys"
      # put cortex api key once cortex is bootstraped
      #- "<cortex_api_key>"
    networks:
      thehive-net:
        ipv4_address: 172.24.0.4

  cassandra:
    image: 'cassandra:4'
    mem_limit: 1000m
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TheHive
    volumes:
      - cassandradata:/var/lib/cassandra
    networks:
      thehive-net:
        ipv4_address: 172.24.0.5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    mem_limit: 512m
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data
    networks:
      thehive-net:
        ipv4_address: 172.24.0.2

  minio:
    image: quay.io/minio/minio
    mem_limit: 512m
    command: ["minio", "server", "/data", "--console-address", ":9090"]
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9090:9090"
    volumes:
      - "miniodata:/data"
    networks:
      thehive-net:
        ipv4_address: 172.24.0.7

  cortex:
    image: thehiveproject/cortex:3.1.7
    environment:
      - job_directory=/tmp/cortex-jobs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/cortex-jobs:/tmp/cortex-jobs
    depends_on:
      - elasticsearch
    ports:
      - "9001:9001"
    networks:
      thehive-net:
        ipv4_address: 172.24.0.3

  grafana:
    image: grafana/grafana:8.2.1
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      - thehive
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      thehive-net:
        ipv4_address: 172.24.0.6

networks:
  thehive-net:
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/16

volumes:
  miniodata:
  cassandradata:
  elasticsearchdata:
  grafana-data:
